services:
  web:
    build: .
    image: php:8.4-apache
    ports:
      - "32770:80"
    volumes:
      - ./html:/var/www/html
      - ./private:/var/www/private
    environment:
      PHP_DISPLAY_ERRORS: 1
      PHP_ERROR_REPORTING: E_ALL
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: studentpass
      MYSQL_DATABASE: dmit2025
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: studentpass
    depends_on:
      - mysql
